#ifndef CSE_HAL_CSE_ERROR_H
#define CSE_HAL_CSE_ERROR_H

#include <cstdint>

namespace cse {

enum class CSError : int32_t {
    SUCCESS = 0,

    ERR_GPIO_INVALID_PIN = 1,
    ERR_GPIO_INVALID_MODE = 2,
    ERR_GPIO_INTERRUPT_FAILED = 3,

    ERR_UART_CONFIG_FAILED = 10,
    ERR_UART_TIMEOUT = 11,
    ERR_UART_BUFFER_OVERFLOW = 12,
    ERR_UART_BUFFER_EMPTY = 13,
    ERR_UART_INVALID_ID = 14,

    ERR_TIMER_INVALID_ID = 20,
    ERR_TIMER_NOT_RUNNING = 21,
    ERR_TIMER_CONFIG_FAILED = 22,

    ERR_WATCHDOG_TIMEOUT = 30,
    ERR_WATCHDOG_INIT_FAILED = 31,

    ERR_VM_STACK_OVERFLOW = 100,
    ERR_VM_STACK_UNDERFLOW = 101,
    ERR_VM_INVALID_OPCODE = 102,
    ERR_VM_INVALID_JUMP = 103,
    ERR_VM_DIVISION_BY_ZERO = 104,
    ERR_VM_NATIVE_CALL_FAILED = 105,
    ERR_VM_CALL_DEPTH_EXCEEDED = 106,
    ERR_VM_INVALID_FUNCTION = 107,
    ERR_VM_TYPE_MISMATCH = 108,

    ERR_FLASH_READ_FAILED = 200,
    ERR_FLASH_WRITE_FAILED = 201,
    ERR_FLASH_ERASE_FAILED = 202,
    ERR_CSB_INVALID_MAGIC = 210,
    ERR_CSB_VERSION_MISMATCH = 211,
    ERR_CSB_INVALID_FUNCTION = 212,
    ERR_CSB_LOAD_FAILED = 213,

    ERR_OUT_OF_MEMORY = 300,
    ERR_NULL_POINTER = 301,
    ERR_HARDWARE_FAULT = 320,
    ERR_INVALID_STATE = 321,

    ERR_FIRMWARE_CRC_FAILED = 400,
    ERR_FIRMWARE_INVALID_HEADER = 401,
};

inline bool isError(CSError err) {
    return err != CSError::SUCCESS;
}

inline bool isSuccess(CSError err) {
    return err == CSError::SUCCESS;
}

const char* getErrorString(CSError err);

}

#endif
